---
- name: Software Install with pip
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: install python packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - ActiveDirectoryEnum
