---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_prompt:
    - name: kali_hostname
      prompt: "New name for this bad boy?"
      private: no


  tasks:
    - name: Set hosts file to user entered value of {{ kali_hostname }}
      lineinfile:
        path: /etc/hosts
        state: present
        regexp: '^127.0.1.1     kali'
        backup: yes
        line: '127.0.1.1        {{ kali_hostname }}'
    - name: Set Hostname to user entered value
      command: 'hostnamectl set-hostname "{{ kali_hostname }}"'
    - name: Reboot system
      command: 'reboot'
