---
- hosts: localhost
  connection: local
  become: true
  gather_facts: true
  vars_prompt:
    - name: kali_hostname
      prompt: "Add or remove? "
      private: no
      
      KexAlgorithms diffie-hellman-group1-sha1,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
Ciphers 3des-cbc,blowfish-cbc,aes128-cbc,aes128-ctr,aes256-ctr
      
      ssh-keygen -A
      
      
#https://www.howtoforge.com/community/threads/enable-diffie-hellman-group1-sha1-on-jessie.70764/#post-337033
      
