---
- name: Change hostname with user input at runtime -e set_hostname=<new_hostname>
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: Set hosts file to user entered value
      lineinfile:
        path: /etc/hosts
        state: present
        regexp: '^127.0.0.1 kali'
        backup: yes
        line: '127.0.0.1  {{ set_hostname }}'
    - name: Set Hostname to user entered value
      command: 'hostnamectl set-hostname "{{ set_hostname }}"'
    - name: Reboot system
      command: 'reboot'
...
#8:22
