---
- name: Change hostname with user input at runtime -e set_hostname=<new_hostname>
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: Set hosts file to user entered value
      lineinfile:
        path: /etc/hosts
        state: present
        search_string: '127.0.1.1       kali'
        line: '127.0.0.1        {{ set_hostname }}'
        #search_string: '127.0.1.kali'
        #line: '127.0.0.1       {{ set_hostname }}'
#        regexp: '^127.0.1.1       kali'
        backup: yes                #may need to remove
#        line: '127.0.1.1       {{ set_hostname }}'
  #  This changes the /etc/hosts file l

        
        
#    - name: Set Hostname to user entered value
#      command: 'hostnamectl set-hostname "{{ set_hostname }}"'
#    - name: Reboot system
#      command: 'reboot'
...
#7:57
