#9:38
---
- name: Change hostname to kali-XX
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
    - name: kali to.......
      lineinfile:
        path: /etc/hosts
        state: present
        regexp: '^%127.0.1.1 kali'
        backup: yes                #may need to remove
        line: '%127.0.1.1 kali-06'
    - name: Set Hostname
      command: 'hostnamectl set-hostname kali-06'
    - name: Reboot system
      command: 'reboot'
...
