---
- name: Apt installs
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  tasks:
#    - debug:
#        msg: "I am connecting to {{ ansible_nodename }} which is running {{ ansible_distribution }} {{ ansible_distribution_version }}"
    - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: uninstall a list of packages
      apt:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - libproxychains3
        - proxychains

    - name: Install a list of packages
      apt:
        pkg:
        - amass
        - apt-file
        - apt-transport-https
        - assetfinder
        - axel
        - autossh
        - bleachbit
        - bloodhound
        - brutespray
        #- bum NA
        - chromium
        - cifs-utils 
        - cme
        #- cntlm
        #- creddump
        - crowbar
        - cryptsetup
        #- code        #requires repo and key be installed first
       #docker        - ca-certificates
        - curl
       # - default-jdka error
        - docker.io
        - dnsmasq
        - dnsrecon
        - dnsutils  
        - ecryptfs-utils
        - exif 
        - exiv2 
        - exfat-fuse 
        #- exfat-utils
        - exploitdb
        - exploitdb-bin-sploits
        - fail2ban
        - fcrackzip
        - feroxbuster
        - figlet
        - filezilla
        - filezilla-common
        - fonts-firacode
        - fonts-noto-color-emoji
      #  - flashplugin-nonfree
        - feroxbuster
        - ffmpeg
        - ffuf
       # - geomview #for clip
        - gdebi
        - gedit
        - gimp
        - git-all
        - gobuster
        - golang
        - grc
#docker        - gnupg-agent
        #- gnome-do NA
        - html2text
        - htop
        - httptunnel
        - impacket-scripts
       # - icedtea-plugin
        - iperf3
        - iptables
        - iptables-persistent
        #- iptables-services #centos only
        - joplin
        - jq
        - jxplorer
        - kali-grant-root
        - knockd
       # - kwartz-client
        - kwrite
        - libimage-exiftool-perl
        - libreoffice-calc
        - libreoffice-gnome 
        - libreoffice-writer 
        - lua5.3
        - lnav
        - logcheck
        - masscan
        - metagoofil
        - medusa
        - mingw-w64
        - multitail
        - nbtscan
        - neo4j
        - neofetch
        - netcat-openbsd 
        - net-tools
        - netfilter-persistent
        - nikto
        - nmap
        - ntpsec-ntpdate
        - nuclei
        - onesixtyone
        - open-iscsi
        - openvpn
        - oscanner 
        - pandoc
        - passing-the-hash
        - photon
        - python3-pip
        - poppler-utils
        - powershell
        - preload
        - proxychains4
        - pure-ftpd
        - putty-tools
        - python3-httpx
        - python3-pip
        - python3-poetry
        - redis-tools
        - rdesktop
        - rinetd
        - ripgrep
        - rlwrap
        - rsync
        - scrub
        - seclists
        #- shutter NA
        - sshfs
        - sipvicious
        - smbclient 
        - smbmap
        - smtp-user-enum
        - snmp 
        - spray
     #docker- software-properties-common
        #- software-center NA
        - sshpass
       # - sshrc #requires additional repo
        - sslscan
        - subfinder
        - sublist3r
        - sudo
        - syncthing
        - synaptic
        - texlive 
        - texlive-latex-extra 
        - texlive-fonts-extra
        - tmux
        - tmuxp
        - tnscmd10g
        - tor
        - tripwire
        - ufw
        - uniscan
        - vim
        - vnstat
        - whatweb
        - whois
        - wkhtmltopdf
        - wireshark
        - wpscan
        - ufw
        - uniscan
        - unicornscan
        - veil
       # - vncsnapshot
        - xclip
        - xdotool
        - xfce4-screenshooter
        - xmlstarlet
        - yersinia
        

        

        

