---
- name: User setup
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  vars_prompt:
    - name: name_user
      prompt: "And this beast of a machine will be called?"
      private: no

    - name: add {{ name_user }} user
      user:
        name: '{{ name_user }}'
        password: '{{ name_user }}'
        groups: sudo
        shell: /bin/bash
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

#    - name: add {{ name_user }} user to sudoers.d
#      lineinfile:
#        path: '/etc/sudoers.d/{{ name_user }}'
#        state: present
#        create: yes
#        regexp: '{{ name_user }} .*'
#        line: '{{ name_user }} ALL=(ALL) NOPASSWD:ALL'

    - name: add {{ name_user }} user to sudoers.d          
      lineinfile:
   #     path: '/etc/sudoers'
        path: '/etc/sudoers.d/{{ name_user }}'
        state: present
        create: yes
        regexp: '{{ name_user }} .*'
        line: '{{ name_user }} ALL=(ALL) NOPASSWD:ALL    #managed by ansible'
        validate: 'visudo -cf %s'
 
